### ISSUE TITLE
State pattern needs state method

### ISSUE THREAD

**Issue by markmc27** [RobbieLD/patterns#1]
I like your Bike example but it doesn't follow my understanding of the State pattern. 

I think the Add and Remove components is a good concept since adding some shocks to a road bike makes it a hybrid, so the state would update from RoadBikeState to HybridBikeState. 

I think the example could go one step further and have a method called "NegotiatePothole()" or something that internally calls `state.NegotiatePothole()`. The outcome (behaviour) of this would then vary depending on the current state of the bike. E.g. if it's a mountain bike, it would ride over it, but if it was a road bike, it would crash or buckle. I think this would make the State example clearer - the Bike remains a Bike but it can be in different states and the behaviour of the bike changes depending on what state it's in.

**Comment by RobbieLD** [comment]
Thanks for pointing this out. I went back and had a look at it and you're right, the example doesn't show the changing functionality of the bike with different states, just that it did change state. I've fixed this like you suggested with a `state.NegotiatePothole()` method. I've also made the state private to the context (`Bike`) as I felt it's probably bad to be able to change the state at any time with out calling a method in the `Bike` to do that. I've created PR https://github.com/RobbieLD/patterns/pull/2 which you can review and see if you think it makes more sense now. You'll need to be added to the project for that so I've sent you an invite :)
